import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import CardGrid from 'components/molecules/CardGrid/CardGrid';

export default {
  title: 'atoms/CardGrid',
  component: CardGrid,
  decorators: [
    storyFn => <div style={{ backgroundColor: 'black' }}>{storyFn()}</div>,
  ],
};

const data = {
  page: 1,
  total_results: 10000,
  total_pages: 500,
  results: [
    {
      popularity: 365.75,
      vote_count: 2585,
      video: false,
      poster_path: '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
      id: 419704,
      adult: false,
      backdrop_path: '/5BwqwxMEjeFtdknRV792Svo0K1v.jpg',
      original_language: 'en',
      original_title: 'Ad Astra',
      genre_ids: [12, 18, 9648, 878, 53],
      title: 'Ad Astra',
      vote_average: 6,
      overview:
        'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
      release_date: '2019-09-17',
    },
    {
      popularity: 328.342,
      vote_count: 680,
      video: false,
      poster_path: '/eFCzU9Jqp2Ea17ysDkG8PB0NLiR.jpg',
      id: 475303,
      adult: false,
      backdrop_path: '/6fkqwqLEcDZOEAnBBfKAniwNxtx.jpg',
      original_language: 'en',
      original_title: 'A Rainy Day in New York',
      genre_ids: [35, 10749],
      title: 'A Rainy Day in New York',
      vote_average: 6.7,
      overview:
        "Two young people arrive in New York to spend a weekend, but once they arrive they're met with bad weather and a series of adventures.",
      release_date: '2019-07-26',
    },
    {
      popularity: 237.255,
      vote_count: 1081,
      video: false,
      poster_path: '/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg',
      id: 454626,
      adult: false,
      backdrop_path: '/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg',
      original_language: 'en',
      original_title: 'Sonic the Hedgehog',
      genre_ids: [28, 35, 878, 10751],
      title: 'Sonic the Hedgehog',
      vote_average: 7.3,
      overview:
        'Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.',
      release_date: '2020-02-12',
    },
    {
      popularity: 195.942,
      vote_count: 2304,
      video: false,
      poster_path: '/bB42KDdfWkOvmzmYkmK58ZlCa9P.jpg',
      id: 512200,
      adult: false,
      backdrop_path: '/hreiLoPysWG79TsyQgMzFKaOTF5.jpg',
      original_language: 'en',
      original_title: 'Jumanji: The Next Level',
      genre_ids: [28, 12, 35, 14],
      title: 'Jumanji: The Next Level',
      vote_average: 6.8,
      overview:
        'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.',
      release_date: '2019-12-04',
    },
    {
      popularity: 190.677,
      vote_count: 3324,
      video: false,
      poster_path: '/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
      id: 530915,
      adult: false,
      backdrop_path: '/cqa3sa4c4jevgnEJwq3CMF8UfTG.jpg',
      original_language: 'en',
      original_title: '1917',
      genre_ids: [18, 10752],
      title: '1917',
      vote_average: 8,
      overview:
        'At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.',
      release_date: '2019-12-25',
    },
    {
      popularity: 252.366,
      vote_count: 0,
      video: false,
      poster_path: '/46UQgss4eeiLt1XE2GpHpPkzjIi.jpg',
      id: 625985,
      adult: false,
      backdrop_path: '/j4B8G5yKRnTO655uvpQBXt4Ok08.jpg',
      original_language: 'ja',
      original_title: '仮面ライダージオウNEXT TIME：ゲイツ、マジェスティ',
      genre_ids: [28, 12, 878],
      title: 'Kamen Rider Zi-O NEXT TIME: Geiz, Majesty',
      vote_average: 0,
      overview:
        'Geiz, Majesty is the first installment of the Kamen Rider Zi-O NEXT TIME series of V-Cinema films for Kamen Rider Zi-O. It focuses on the character Geiz Myokoin.',
      release_date: '2020-04-22',
    },
    {
      popularity: 209.734,
      vote_count: 134,
      video: false,
      poster_path: '/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg',
      id: 338762,
      adult: false,
      backdrop_path: '/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg',
      original_language: 'en',
      original_title: 'Bloodshot',
      genre_ids: [28, 18, 14, 878],
      title: 'Bloodshot',
      vote_average: 5.8,
      overview:
        "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine - Bloodshot. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
      release_date: '2020-02-20',
    },
    {
      popularity: 181.185,
      vote_count: 2921,
      video: false,
      poster_path: '/pjeMs3yqRmFL3giJy4PMXWZTTPa.jpg',
      id: 330457,
      adult: false,
      backdrop_path: '/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg',
      original_language: 'en',
      original_title: 'Frozen II',
      genre_ids: [12, 16, 10751],
      title: 'Frozen II',
      vote_average: 7.1,
      overview:
        'Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.',
      release_date: '2019-11-20',
    },
    {
      popularity: 162.216,
      vote_count: 2638,
      video: false,
      poster_path: '/kbC6I0AOSLTHFA2dieyat9h8QHP.jpg',
      id: 39538,
      adult: false,
      backdrop_path: '/57kqAPdVJTAJ4rnDTSVDx0f1JBu.jpg',
      original_language: 'en',
      original_title: 'Contagion',
      genre_ids: [18, 878, 53],
      title: 'Contagion',
      vote_average: 6.4,
      overview:
        'As an epidemic of a lethal airborne virus - that kills within days - rapidly grows, the worldwide medical community races to find a cure and control the panic that spreads faster than the virus itself.',
      release_date: '2011-09-08',
    },
    {
      popularity: 145.807,
      vote_count: 1395,
      video: false,
      poster_path: '/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg',
      id: 495764,
      adult: false,
      backdrop_path: '/2s1ofreBI8EFzIyL3SQrLRqO5Zx.jpg',
      original_language: 'en',
      original_title:
        'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
      genre_ids: [28, 35, 80],
      title:
        'Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)',
      vote_average: 6.9,
      overview:
        'After her breakup with the Joker, Harley Quinn joins forces with singer Black Canary, assassin Huntress, and police detective Renee Montoya to help a young girl named Cassandra, who had a hit placed on her after she stole a rare diamond from crime lord Roman Sionis.',
      release_date: '2020-02-05',
    },
    {
      popularity: 136.567,
      vote_count: 9936,
      video: false,
      poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
      id: 475557,
      adult: false,
      backdrop_path: '/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
      original_language: 'en',
      original_title: 'Joker',
      genre_ids: [80, 18, 53],
      title: 'Joker',
      vote_average: 8.2,
      overview:
        'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
      release_date: '2019-10-02',
    },
    {
      popularity: 114,
      vote_count: 5250,
      video: false,
      poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
      id: 496243,
      adult: false,
      backdrop_path: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
      original_language: 'ko',
      original_title: '기생충',
      genre_ids: [35, 18, 53],
      title: 'Parasite',
      vote_average: 8.5,
      overview:
        "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
      release_date: '2019-05-30',
    },
    {
      popularity: 111.922,
      vote_count: 392,
      video: false,
      poster_path: '/fePczipv6ZzDO2uoww4vTAu2Sq3.jpg',
      id: 581600,
      adult: false,
      backdrop_path: '/ftODZXaXpWtV5XFD8gS9n9KwLDr.jpg',
      original_language: 'en',
      original_title: 'Spenser Confidential',
      genre_ids: [28, 35, 53],
      title: 'Spenser Confidential',
      vote_average: 6.7,
      overview:
        'Spenser, a former Boston patrolman who just got out from prison, teams up with Hawk, an aspiring fighter, to unravel the truth behind the death of two police officers.',
      release_date: '2020-03-06',
    },
    {
      popularity: 107.827,
      vote_count: 8827,
      video: false,
      poster_path: '/jpfkzbIXgKZqCZAkEkFH2VYF63s.jpg',
      id: 920,
      adult: false,
      backdrop_path: '/a1MlbLBk5Sy6YvMbSuKfwGlDVlb.jpg',
      original_language: 'en',
      original_title: 'Cars',
      genre_ids: [12, 16, 35, 10751],
      title: 'Cars',
      vote_average: 6.7,
      overview:
        "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
      release_date: '2006-06-08',
    },
    {
      popularity: 81.396,
      vote_count: 212,
      video: false,
      poster_path: '/vN7JHlHOT9rHNDU27tfYqhABBj5.jpg',
      id: 465086,
      adult: false,
      backdrop_path: '/h4x5aN52nq78PM8zXD77THhZTB.jpg',
      original_language: 'en',
      original_title: 'The Grudge',
      genre_ids: [27, 9648],
      title: 'The Grudge',
      vote_average: 5.4,
      overview:
        'After a young mother murders her family in her own house, a detective attempts to investigate the mysterious case, only to discover that the house is cursed by a vengeful ghost. Now targeted by the demonic spirits, the detective must do anything to protect herself and her family from harm.',
      release_date: '2020-01-02',
    },
    {
      popularity: 73.378,
      vote_count: 2784,
      video: false,
      poster_path: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
      id: 546554,
      adult: false,
      backdrop_path: '/cjTQSwcsfVdirSFSHNBXRGkxmWa.jpg',
      original_language: 'en',
      original_title: 'Knives Out',
      genre_ids: [35, 9648],
      title: 'Knives Out',
      vote_average: 7.8,
      overview:
        "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
      release_date: '2019-11-27',
    },
    {
      popularity: 90.006,
      vote_count: 1882,
      video: false,
      poster_path: '/6ApDtO7xaWAfPqfi2IARXIzj8QS.jpg',
      id: 359724,
      adult: false,
      backdrop_path: '/n3UanIvmnBlH531pykuzNs4LbH6.jpg',
      original_language: 'en',
      original_title: 'Ford v Ferrari',
      genre_ids: [28, 18],
      title: 'Ford v Ferrari',
      vote_average: 7.8,
      overview:
        'American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.',
      release_date: '2019-11-13',
    },
    {
      popularity: 98.802,
      vote_count: 426,
      video: false,
      poster_path: '/4U7hpTK0XTQBKT5X60bKmJd05ha.jpg',
      id: 570670,
      adult: false,
      backdrop_path: '/uZMZyvarQuXLRqf3xdpdMqzdtjb.jpg',
      original_language: 'en',
      original_title: 'The Invisible Man',
      genre_ids: [27, 878, 53],
      title: 'The Invisible Man',
      vote_average: 7.1,
      overview:
        "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see.",
      release_date: '2020-02-26',
    },
    {
      popularity: 140.287,
      vote_count: 3231,
      video: false,
      poster_path: '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
      id: 181812,
      adult: false,
      backdrop_path: '/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg',
      original_language: 'en',
      original_title: 'Star Wars: The Rise of Skywalker',
      genre_ids: [28, 12, 878],
      title: 'Star Wars: The Rise of Skywalker',
      vote_average: 6.5,
      overview:
        'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
      release_date: '2019-12-18',
    },
    {
      popularity: 79.645,
      vote_count: 368,
      video: false,
      poster_path: '/30YacPAcxpNemhhwX0PVUl9pVA3.jpg',
      id: 431693,
      adult: false,
      backdrop_path: '/qlYxtqVfu2LOdvYMMDPCSGX0Oz0.jpg',
      original_language: 'en',
      original_title: 'Spies in Disguise',
      genre_ids: [28, 12, 16, 35],
      title: 'Spies in Disguise',
      vote_average: 7.3,
      overview:
        'Super spy Lance Sterling and scientist Walter Beckett are almost exact opposites. Lance is smooth, suave and debonair. Walter is… not. But what Walter lacks in social skills he makes up for in smarts and invention, creating the awesome gadgets Lance uses on his epic missions. But when events take an unexpected turn, Walter and Lance suddenly have to rely on each other in a whole new way.',
      release_date: '2019-12-24',
    },
  ],
};

export const Primary = () => (
  <BrowserRouter>
    <CardGrid data={data} />
  </BrowserRouter>
);
